version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: developement
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    ports:
      - 8000:8000
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:16
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - mynetwork

  admin:
    build:
      dockerfile: Dockerfile.dev
      context: "./dashboard"
    environment:
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dq2hgf98y
    depends_on:
      - server
    ports:
      - 3001:3001
    networks:
      - mynetwork

  store:
    build:
      context: ./store
      dockerfile: Dockerfile.dev
    depends_on:
      - server
      - admin
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dq2hgf98y
      - NEXT_PUBLIC_BASE_URL='http://localhost:8000/v1'
    networks:
      - mynetwork

volumes:
  postgres:
networks:
  mynetwork:
    driver: bridge
