version: "3"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: developement
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8000:8000
    command: npm run dev
volumes:
  postgres:
